# Generated by Django 4.2.1 on 2023-05-27 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('content', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
