# Generated by Django 4.2.1 on 2024-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedcontent',
            name='isgenerated',
            field=models.BooleanField(default=False),
        ),
    ]
