# Generated by Django 4.2.1 on 2024-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_relatedcontent_isgenerated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
