# Generated by Django 4.2.1 on 2024-06-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teacher_testing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='allow_insight_suggestion',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='similiarity_threshold',
            new_name='threshold',
        ),
    ]
