# Generated by Django 4.2.1 on 2023-10-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_course_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonNumber',
            field=models.IntegerField(default=1),
        ),
    ]
