# Generated by Django 4.2.1 on 2023-10-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lesson_lessonnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
