# Generated by Django 4.2.1 on 2023-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lesson_lessonnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subtitle',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
