# Generated by Django 4.2.1 on 2023-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='question',
        ),
        migrations.RemoveField(
            model_name='query',
            name='response',
        ),
        migrations.AddField(
            model_name='query',
            name='subqueries',
            field=models.ManyToManyField(to='api.subquery'),
        ),
    ]
