# Generated by Django 4.2.1 on 2023-10-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subquery_remove_query_question_remove_query_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(upload_to='media')),
                ('lesson_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessoncontent')),
            ],
        ),
    ]
