# Generated by Django 4.2.1 on 2023-11-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_files', to='api.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='api.file'),
        ),
    ]
