# Generated by Django 4.2.1 on 2023-11-08 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_query_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
