# Generated by Django 4.2.1 on 2024-05-18 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
