# Generated by Django 4.2.1 on 2024-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_notification_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
